services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123vanduc
      POSTGRES_DB: demo
    ports:
      - 5432:5432
    networks:
      - shop-network
  shop-app-api:
    container_name: shop-app-api
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - shop-network
  shop-app-front:
    container_name: shop-app-front
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - shop-network
networks:
  shop-network:
    driver: bridge
