export { default as Home } from './Home/Home';
export { default as Register } from './Register';
export { default as Login } from './Login';
export { default as Product } from './Product/Product';
export { default as Cart } from './Cart/Cart';
export { default as Search } from './Search/Search';
export { default as Category } from './Category/Category';
export { default as Error } from './Error/Error';
export { default as Checkout } from './Checkout';
export * from './User';
