POSTGRES_SQL_USERNAME: postgres
POSTGRES_SQL_PASSWORD: 123vanduc
POSTGRES_SQL_URL: jdbc:postgresql://postgres:5432/demo

#SERVER
SERVER_PORT: 8080
CLIENT_URL: http://localhost:3000

#VNPAY
VNPAY_TMNCODE: 6SBN9I5G
VNPAY_SECRET: CZOENDQGM8R1U2DW20Y5B49E1YXEIJ1M
VNPAY_URL: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html

#REDIS
REDIS_PORT: 6379
REDIS_HOSTNAME: localhost

#EMAIL CONFIG
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: ducnbk7a1@gmail.com
EMAIL_PASSWORD: lqdu zcio dwur iyup
VERIFY_EMAIL_HOST: http://localhost:${SERVER_PORT}


