name: Docker Image CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  update-backend:
    name: Build & push back-end image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log into Docker Hub
        run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin

      - name: Build Backend Docker Image
        run: docker build ./backend -t "${{secrets.DOCKER_USERNAME}}/shop-app-api"

      - name: Push Backend Image
        run: docker push "${{secrets.DOCKER_USERNAME}}/shop-app-api"
  update-frontend:
    name: Build & push front-end image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log into Docker Hub
        run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin

      - name: Build Frontend Docker Image
        run: docker build ./frontend -t "${{secrets.DOCKER_USERNAME}}/shop-app-front"

      - name: Push Frontend Image
        run: docker push "${{secrets.DOCKER_USERNAME}}/shop-app-front"
